// This file will be auto-generated by Supabase CLI
// For now, we'll use a placeholder type
// Run: npx supabase gen types typescript --project-id <project-id> > src/types/database.ts

export type Database = {
  public: {
    Tables: {
      profiles: any;
      events: any;
      friendships: any;
      event_participants: any;
      groups: any;
      group_members: any;
      notifications: any;
      calendar_connections: any;
    };
    Views: {};
    Functions: {};
    Enums: {};
  };
};
